apiVersion: v1
kind: Pod
metadata:
  name: private-hello-world
spec:
  containers:
  - name: private-hello-container
    image: gurjeet.azurecr.io/gurjeetself:7
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: mydocker
