{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: nginx
{{- end }}
