apiVersion: v1
appVersion: "1.0"
description: A simple ghost
name: kubernetes-configmap
home: http://www.9spokes.com/
maintainers:
- email: gurjeetsahi@gmail.com
  name: Gurjeet Singh
version: 0.1.0

